-- ============================================================
--  Servicom Group · Esquema de base de datos para Supabase
--  Pégalo completo en: Supabase → SQL Editor → New query → Run
--  Es seguro ejecutarlo más de una vez.
-- ============================================================

-- ---------- 1. TABLAS ----------

create table if not exists public.products (
  id           bigint primary key generated by default as identity,
  name         text           not null,
  category     text           not null,
  price        numeric(10,2)  not null check (price >= 0),
  stock        integer        not null default 0 check (stock >= 0),
  active       boolean        not null default true,
  icon         text           not null default '📦',
  description  text           not null default '',
  icon_image   text,                          -- URL pública del icono (Storage)
  image        text,                          -- URL de la primera imagen de detalle
  detail_images text[]        not null default '{}',
  created_at   timestamptz    not null default now()
);

create sequence if not exists public.orders_seq start 1000;

create table if not exists public.orders (
  id           text primary key,                          -- SG-20261009-1000
  access_token uuid not null default gen_random_uuid(),   -- "llave" del cliente para ver su pedido
  created_at   timestamptz   not null default now(),
  customer     jsonb         not null,
  items        jsonb         not null,
  total        numeric(10,2) not null check (total >= 0),
  status       text          not null default 'Confirmado'
               check (status in ('Confirmado','Despachando','Enviando','Entregado'))
);

-- Quién es administrador (se llena a mano, ver paso 3 de la guía)
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

-- ---------- 2. FUNCIÓN is_admin() ----------

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- ---------- 3. SEGURIDAD (RLS) ----------

alter table public.products enable row level security;
alter table public.orders   enable row level security;
alter table public.admins   enable row level security;   -- sin políticas: nadie la lee desde la API

drop policy if exists "products_select" on public.products;
drop policy if exists "products_admin_insert" on public.products;
drop policy if exists "products_admin_update" on public.products;
drop policy if exists "products_admin_delete" on public.products;
drop policy if exists "orders_admin_all" on public.orders;

-- Clientes ven solo productos activos; el admin ve todos
create policy "products_select" on public.products
  for select to anon, authenticated
  using (active = true or public.is_admin());

create policy "products_admin_insert" on public.products
  for insert to authenticated with check (public.is_admin());
create policy "products_admin_update" on public.products
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "products_admin_delete" on public.products
  for delete to authenticated using (public.is_admin());

-- Pedidos: solo el admin accede directo a la tabla.
-- Los clientes usan las funciones create_order() y get_my_orders().
create policy "orders_admin_all" on public.orders
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- 4. CREAR PEDIDO (atómico y validado en el servidor) ----------
-- Recalcula precios desde la base y descuenta stock con bloqueo de fila,
-- así nadie puede manipular precios ni vender stock que no existe.

create or replace function public.create_order(p_customer jsonb, p_items jsonb)
returns jsonb
language plpgsql security definer
set search_path = public
as $$
declare
  v_item   jsonb;
  v_prod   public.products;
  v_qty    integer;
  v_items  jsonb := '[]'::jsonb;
  v_total  numeric(10,2) := 0;
  v_cust   jsonb;
  v_id     text;
  v_order  public.orders;
begin
  if p_customer is null
     or coalesce(p_customer->>'dni','')   !~ '^[0-9]{8}$'
     or coalesce(p_customer->>'phone','') !~ '^[0-9]{9}$'
     or length(trim(coalesce(p_customer->>'name','')))    not between 1 and 120
     or length(trim(coalesce(p_customer->>'email','')))   not between 3 and 120
     or length(trim(coalesce(p_customer->>'address','')))  not between 1 and 300
  then
    raise exception 'Los datos de entrega no son válidos';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Tu carrito está vacío';
  end if;

  v_cust := jsonb_build_object(
    'dni',     p_customer->>'dni',
    'phone',   p_customer->>'phone',
    'name',    trim(p_customer->>'name'),
    'email',   trim(p_customer->>'email'),
    'address', trim(p_customer->>'address')
  );

  -- Se recorre ordenado por id para evitar bloqueos cruzados entre compras simultáneas
  for v_item in
    select e from jsonb_array_elements(p_items) e order by (e->>'id')::bigint
  loop
    v_qty := (v_item->>'qty')::integer;
    if v_qty is null or v_qty < 1 or v_qty > 1000 then
      raise exception 'Cantidad inválida';
    end if;

    select * into v_prod from public.products
     where id = (v_item->>'id')::bigint
     for update;

    if not found or not v_prod.active then
      raise exception 'Uno de los productos ya no está disponible';
    end if;
    if v_prod.stock < v_qty then
      raise exception 'Stock insuficiente para "%": quedan % unidades', v_prod.name, v_prod.stock;
    end if;

    update public.products set stock = stock - v_qty where id = v_prod.id;

    v_items := v_items || jsonb_build_object(
      'id', v_prod.id, 'name', v_prod.name, 'price', v_prod.price, 'qty', v_qty);
    v_total := v_total + v_prod.price * v_qty;
  end loop;

  v_id := 'SG-' || to_char(now() at time zone 'America/Lima', 'YYYYMMDD')
          || '-' || nextval('public.orders_seq');

  insert into public.orders (id, customer, items, total)
  values (v_id, v_cust, v_items, v_total)
  returning * into v_order;

  return jsonb_build_object(
    'id', v_order.id, 'date', v_order.created_at, 'customer', v_order.customer,
    'items', v_order.items, 'total', v_order.total, 'status', v_order.status,
    'token', v_order.access_token);
end;
$$;

revoke all on function public.create_order(jsonb, jsonb) from public;
grant execute on function public.create_order(jsonb, jsonb) to anon, authenticated;

-- ---------- 5. VER MIS PEDIDOS (el cliente presenta sus "llaves") ----------

create or replace function public.get_my_orders(p_tokens uuid[])
returns jsonb
language sql stable security definer
set search_path = public
as $$
  select coalesce(
    jsonb_agg(jsonb_build_object(
      'id', id, 'date', created_at, 'customer', customer, 'items', items,
      'total', total, 'status', status, 'token', access_token
    ) order by created_at desc),
    '[]'::jsonb)
  from public.orders
  where access_token = any(p_tokens);
$$;

revoke all on function public.get_my_orders(uuid[]) from public;
grant execute on function public.get_my_orders(uuid[]) to anon, authenticated;

-- ---------- 6. ALMACENAMIENTO DE IMÁGENES ----------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880,
        array['image/png','image/jpeg','image/webp'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "product_images_admin_insert" on storage.objects;
drop policy if exists "product_images_admin_update" on storage.objects;
drop policy if exists "product_images_admin_delete" on storage.objects;

create policy "product_images_admin_insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'product-images' and public.is_admin());
create policy "product_images_admin_update" on storage.objects
  for update to authenticated
  using (bucket_id = 'product-images' and public.is_admin());
create policy "product_images_admin_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'product-images' and public.is_admin());

-- ---------- 7. PRODUCTOS DE DEMOSTRACIÓN ----------

insert into public.products (id, name, category, price, stock, active, icon, description) values
 (1,'Laptop Lenovo IdeaPad 3','Laptops',1899.90,12,true,'💻','Laptop para trabajo y estudio con pantalla de 15.6 pulgadas, procesador eficiente y almacenamiento SSD.'),
 (2,'Laptop HP 15','Laptops',2199.90,8,true,'🖥️','Equipo portátil de 15.6 pulgadas pensado para productividad, clases virtuales y oficina.'),
 (3,'Monitor LG 24 pulgadas','Monitores',699.90,15,true,'🖥️','Monitor Full HD de 24 pulgadas, ideal para oficina, diseño y entretenimiento.'),
 (4,'Teclado Mecánico Redragon','Periféricos',179.90,20,true,'⌨️','Teclado mecánico con iluminación y diseño compacto para trabajo y gaming.'),
 (5,'Mouse Logitech inalámbrico','Periféricos',89.90,30,true,'🖱️','Mouse inalámbrico cómodo para oficina y uso diario.'),
 (6,'Audífonos Sony Bluetooth','Audio',349.90,10,true,'🎧','Audífonos inalámbricos con conexión Bluetooth y sonido de alta calidad.'),
 (7,'SSD Kingston 1 TB','Almacenamiento',329.90,18,true,'💾','Unidad SSD de 1 TB para acelerar el almacenamiento y arranque del equipo.'),
 (8,'Router TP-Link WiFi 6','Redes',299.90,14,true,'📡','Router WiFi 6 para una conexión estable y rápida en hogares y oficinas.'),
 (9,'Webcam Logitech C920','Accesorios',299.90,9,true,'📷','Webcam Full HD para videollamadas, reuniones y clases virtuales.'),
 (10,'Impresora Epson EcoTank','Impresoras',849.90,7,true,'🖨️','Impresora multifunción con sistema de tanque de tinta de alto rendimiento.')
on conflict (id) do nothing;

-- Para que los productos nuevos continúen desde el id 11
select setval(pg_get_serial_sequence('public.products','id'),
              greatest((select max(id) from public.products), 10));

-- ============================================================
--  PASO MANUAL (después de crear tu usuario en Authentication → Users):
--  convierte ese usuario en administrador cambiando el correo:
--
--  insert into public.admins (user_id)
--  select id from auth.users where email = 'TU_CORREO@ejemplo.com'
--  on conflict do nothing;
-- ============================================================
