function checkout(){if(!cart.length)return toast("Tu carrito está vacío");$("#checkoutContent").innerHTML=`<div class="checkout-steps"><span class="step active">1. Datos</span><span class="step">2. Pago</span><span class="step">3. Voucher</span></div><p class="eyebrow">DATOS DE ENTREGA</p><h2>Completa tu compra</h2><form id="customerForm" class="form-grid"><label>DNI<input name="dni" pattern="[0-9]{8}" maxlength="8" required></label><label>Teléfono<input name="phone" pattern="[0-9]{9}" maxlength="9" required></label><label>Nombre completo<input name="name" required></label><label>Correo<input name="email" type="email" required></label><label class="span-2">Dirección de envío<textarea name="address" required></textarea></label><div class="span-2"><div class="total-row"><span>Total</span><strong>${money(totalCart())}</strong></div></div><button class="primary-btn span-2">Continuar al pago</button></form>`;$("#checkoutModal").classList.remove("hidden");$("#customerForm").onsubmit=e=>{e.preventDefault();showPayment(Object.fromEntries(new FormData(e.target)))}}
function showPayment(c){const total=totalCart();$("#checkoutContent").innerHTML=`<div class="checkout-steps"><span class="step done">1. Datos ✓</span><span class="step active">2. Pago</span><span class="step">3. Voucher</span></div><p class="eyebrow">PAGO SIMULADO</p><h2>Pago con tarjeta</h2><div class="payment-card"><div class="form-grid"><label>Número de tarjeta<input id="card" maxlength="19" placeholder="4111 1111 1111 1111"></label><label>Nombre en tarjeta<input id="cardName"></label><label>Vencimiento<input id="exp" maxlength="5" placeholder="MM/AA"></label><label>CVV<input id="cvv" maxlength="4"></label></div></div><div class="checkout-summary"><span>Monto a cargar</span><strong>${money(total)}</strong></div><p class="order-detail">Simulación: no se realiza ningún cargo real.</p><button class="primary-btn full" id="payBtn">Pagar ${money(total)}</button>`;$("#payBtn").onclick=()=>finishPayment(c)}
async function finishPayment(c){
  const btn=$("#payBtn"),label=btn.textContent;
  btn.disabled=true;btn.textContent="Procesando...";
  try{
    const o=await apiCreateOrder(c,cart.map(i=>({id:i.id,qty:i.qty})));
    cart=[];saveCart();showVoucher(o);
  }catch(err){
    console.error(err);
    toast(err.message||"No se pudo registrar el pedido");
    try{await refreshDB()}catch(e){console.warn(e)}
    syncCartWithCatalog();renderCart();updateCount();renderProducts();
    btn.disabled=false;btn.textContent=label;
  }
}
function showVoucher(o){$("#checkoutContent").innerHTML=`<div class="checkout-steps"><span class="step done">1. Datos ✓</span><span class="step done">2. Pago ✓</span><span class="step active">3. Voucher</span></div><p class="eyebrow">CONSTANCIA DE DEMOSTRACIÓN</p><h2>Compra registrada</h2><div class="voucher"><h3>VOUCHER DE VENTA — DEMO</h3><div class="line"></div><p>Empresa: Servicom Group</p><p>Pedido: ${o.id}</p><p>Fecha: ${new Date(o.date).toLocaleString("es-PE")}</p><div class="line"></div>${o.items.map(i=>`<p>${escapeHTML(i.name)} x${i.qty} — ${money(i.price*i.qty)}</p>`).join("")}<div class="line"></div><p><b>TOTAL: ${money(o.total)}</b></p><p>Cliente: ${escapeHTML(o.customer.name)}</p><p>DNI: ${escapeHTML(o.customer.dni)}</p><p>Dirección: ${escapeHTML(o.customer.address)}</p><div class="line"></div><p style="text-align:center">DOCUMENTO SIMULADO — SIN VALIDEZ TRIBUTARIA</p></div><button id="afterVoucher" class="primary-btn full">Ver mis pedidos</button>`;$("#afterVoucher").onclick=()=>{closeAll();openOrders()};renderProducts()}
